spring:
  application:
    name: microservice1  # Nome do microserviço
  profiles:
    active: dev  # Perfil ativo, como dev, prod, etc.
  cloud:
    config:
      uri: http://<config-server-url>  # URL do Config Server
      name: product1/microservice1  # Nome que considera o produto e microserviço
      fail-fast: true  # Se o Config Server não estiver disponível, a aplicação falhará ao iniciar
  product: product1  # Nome do produto
